# Generated by Django 5.0 on 2023-12-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseCode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('Course_Department', models.CharField(choices=[('CSE-H', 'CSE(HOUNORS)'), ('CSE-R', 'CSE(REGULARS)'), ('ECE', 'ECE'), ('BT', 'BT'), ('CS-IT', 'CS-IT'), ('AI&DS', 'AI&DS')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('FacultyName', models.CharField(max_length=200)),
                ('Mobile_Number', models.BigIntegerField()),
                ('Faculty_department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('BT', 'BT')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=200)),
                ('Mobile_Number', models.BigIntegerField()),
                ('Student_department', models.CharField(choices=[('CSE-H', 'CSE(HOUNORS)'), ('CSE-R', 'CSE(REGULARS)'), ('ECE', 'ECE'), ('BT', 'BT'), ('CS-IT', 'CS-IT'), ('AI&DS', 'AI&DS')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unknown', 'Unknown'), ('student', 'Student'), ('faculty', 'Faculty')], default='unknown', max_length=20)),
                ('faculty_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty', to='demoapp.faculty')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='demoapp.student')),
            ],
        ),
    ]
