# Generated by Django 5.0 on 2023-12-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_DET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unknown', 'Unknown'), ('student', 'Student'), ('faculty', 'Faculty')], default='unknown', max_length=20)),
                ('faculty_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty', to='demoapp.faculty')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='demoapp.student')),
            ],
        ),
    ]
