# Generated by Django 5.0 on 2023-12-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_user_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='faculty_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty', to='demoapp.faculty'),
        ),
        migrations.AlterField(
            model_name='user_det',
            name='student_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='demoapp.student'),
        ),
    ]
