# Generated by Django 5.0 on 2023-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_user_det_faculty_id_alter_user_det_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_det',
            name='password',
            field=models.CharField(default='klu@123', max_length=100),
        ),
    ]
