# Generated by Django 5.0 on 2023-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_user_det_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='role',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'admin')], default='unknown', max_length=20),
        ),
    ]
