# Generated by Django 5.0 on 2023-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_alter_user_det_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_det',
            name='admin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
