# Generated by Django 5.0 on 2023-12-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_user_det_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_det',
            old_name='admin_id',
            new_name='adminuname',
        ),
    ]
