# Generated by Django 5.0 on 2023-12-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_rename_admin_id_user_det_adminuname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_det',
            old_name='adminuname',
            new_name='adminusr',
        ),
    ]
